[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = ["lib/cairo-contracts/src"] 


[contracts]
main = ["src/zkx-hack.cairo"]

# Shared Configuration Profile
[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321

[profile.testnet.project]
network = "testnet"
